### PR TITLE
fix: handle module resolution errors with --watch

### LINKED ISSUE #34: Watcher throws bland message when importing nonexistent module
When `mod.ts` imports `nonexistent.ts`:

```
> deployctl run mod.ts --watch
error: Uncaught (in promise) NotFound: No such file or directory (os error 2)
    const watcher = Deno.watchFs(deps);
^
    at handleError (deno:core/core.js:186:12)
    at jsonOpParseResult (deno:core/core.js:356:9)
    at opSync (deno:core/core.js:259:32)
    at Object.jsonOpSync (deno:core/core.js:372:12)
    at new FsWatcher (deno:runtime/js/40_fs_events.js:13:24)
    at Object.watchFs (deno:runtime/js/40_fs_events.js:49:12)
    at watch (https://deno.land/x/deploy@0.1.0/src/subcommands/run.ts:108:1)
    at async default (https://deno.land/x/deploy@0.1.0/src/subcommands/run.ts:89:1)
    at async https://deno.land/x/deploy@0.1.0/deployctl.ts:61:1
```

Comparatively, `deno cache` shows the actual issue:

```
> deno cache mod.ts 
error: Cannot resolve module "file:///work/nonexistent.ts" from "file:///work/mod.ts".
    at file:///work/mod.ts:1:0
```

This is a trivial example, which can be less obvious when refactoring files in a larger project with the watcher running.

### PR DESCRIPTION
**Pull request by lucacasonato**
This commit fixes module resolution errors being swallowed in --watch,
and resulting in a non descript "Not Found" error. This commit correctly
handles and displays these errors.

Fixes #34

### CODE REVIEW

File: src/utils/info.ts [hunk 1]
```diff
@@ -1,10 +1,19 @@
 import { fromFileUrl } from "../../deps.ts";
 
+export class ModuleGraphError extends Error {
```
Comment (kt3k) [inline src/utils/info.ts:3]: seems not used?

Comment (lucacasonato) [reply src/utils/info.ts:3]: Ah yes. Forgot to remove

**Review by kt3k — APPROVED** [review]
Other part looks good to me
