### PR TITLE
fix(action): address test failures

### LINKED ISSUE #319: `Deploy to Deno Deploy` fails with TypeError
Current main branch fails to pass the CI

```
Project: happy-rat-64
Entrypoint: file:///src/hello.ts
Import map: file:///src/import_map.json
Uploading 0 file(s) (total 0 bytes)
Error: TypeError: progress is not async iterable
```

https://github.com/denoland/deployctl/actions/runs/10061940442/job/27813205720

### PR DESCRIPTION
**Pull request by magurotuna**
- add `await` to deal with a floating promise
- exclude `node_modules` from deployment assets by default

Resolves #319

### CODE REVIEW

File: action/index.js [hunk 1]
```diff
@@ -73,14 +73,16 @@ async function main() {
   }
 
   core.debug(`Discovering assets in "${cwd}"`);
+  const includes = include.flatMap((i) => i.split(","));
+  const excludes = exclude.flatMap((e) => e.split(","));
+  // Exclude node_modules by default unless explicitly specified
+  if (!includes.some((i) => i.includes("node_modules"))) {
+    excludes.push("**/node_modules");
+  }
```
Comment (magurotuna) [inline action/index.js:81]: Prior to #317, `action/deps.js` was manually modified to exclude node_modules (see [#222](https://github.com/denoland/deployctl/pull/222/files#diff-f9f204a50fc8382442bcf662817c45a184b73283ee9369b98b19369526df0334R4039)). #317 overwrote this manual change and has caused `Always exclude node_modules directory` test case to fail. To fix this, I added node_modules to `exclude` in the same way as https://github.com/denoland/deployctl/blob/acb2ba33df6b146bc8705a1d1c16283d9fef9e78/src/config_inference.ts#L235-L237

**Review by arnauorriols — APPROVED** [review]
LGTM
